export const developerDetails = [
  {
    title: "Ra Preeti Krishnaveni",
    title1: "Frontend",
    img: "Dev/Preeti.jpg",
    href: "https://www.linkedin.com/in/preeti-krishnaveni-a1b9201aa/",
  },
  {
    title: "Sneha S",
    title1: "Frontend",
    img: "Dev/Sneha S.png",
    href: "https://www.linkedin.com/in/sneha-s-0766761ab/?trk=public_profile_browsemap&originalSubdomain=in",
  },
  {
    title: "Sanjeev Karthick K",
    title1: "Frontend",
    img: "Dev/Sanjeev.jpg",
    href: "https://www.linkedin.com/in/sanjeev-karthick-96910571/",
  },
  {
    title: "Shafeeq Ur Rahman P A",
    title1: "Frontend",
    img: "Dev/Shafeeq Ur Rahman P A.png",
    href: "https://www.linkedin.com/in/darrshana-rajkumar-6a36aa1ba",
  },
  {
    title: "Sreeratcha B",
    title1: "Frontend",
    img: "Dev/Sree.jpg",
    href: "https://www.linkedin.com/in/sreeratcha-b-5a8026195",
  },
  {
    title: "Anusree V",
    title1: "Frontend",
    img: "Dev/Anu.jpg",
    href: "https://www.linkedin.com/in/anusree-varadharaj-bb43471a1",
  },
  {
    title: "Jyotir Aditya Giri A",
    title1: "Frontend",
    img: "Dev/Jyotir Aditya Giri A.png",
    href: "https://www.linkedin.com/in/jyotir-aditya-giri",
  },
  {
    title: "Pranava Raman BMS",
    title1: "Backend",
    img: "Dev/Pranava Raman BMS.jpg",
    href: "https://www.linkedin.com/in/pranava-raman-bms/",
  },
  {
    title: "Ajitesh M",
    title1: "Backend",
    img: "Dev/Ajitesh M.jpg",
    href: "https://www.linkedin.com/in/ajitesh-mahalingam",
  },
  {
    title: "Safiya Fathima Syed",
    title1: "Backend",
    img: "Dev/Safiya Fathima Syed.png",
    href: "https://www.linkedin.com/in/safiya-fathima-syed",
  },
  {
    title: "Diya Dhandapani",
    title1: "Backend",
    img: "Dev/Diya.png",
    href: "https://www.linkedin.com/in/diya-dhandapani",
  },
  {
    title: "Bharath M",
    title1: "Design",
    img: "Dev/Bharath M.png",
    href: "https://www.linkedin.com/in/bharath-mohan-65a51020b/",
  },
  {
    title: "AKASH MURUGESH K",
    title1: "Design",
    img: "Dev/Akash.jpg",
    href: "https://www.linkedin.com/in/akashmurugesh/",
  },
];
